theme = "re-terminal"
[params]
  displayFullLangName = true


[languages]
  [languages.en]
    languageCode = 'en'
    languageName = 'English'
    title = 'Zomggang dev Blog'
    weight = 1
  [languages.ko]
    languageName = '한국어'
    title = '좀깡월드'
  [languages.jp]
    languageCode = 'zh-TW'
    languageName = '日本語'
    title = 'Zomggang開発ブログ'
    weight = 3