baseURL = 'https://jo-gangeun.github.io/zomggang-devblog/'
title = 'Zomggang Devblog'
theme = 're-terminal'
languageCode = 'ko'
defaultContentLanguage = 'ko'
defaultContentLanguageInSubdir = true

[languages]

[languages.ko]
languageName = "한국어"
weight = 1
contentDir = "content/ko"

[languages.en]
languageName = "English"
weight = 2
contentDir = "content/en"

[languages.ja]
languageName = "日本語"
weight = 3
contentDir = "content/jp"
